---
url: http://componentkit.org
name: ComponentKit
description: A React-inspired view framework for iOS
timezone: America/Los_Angeles

safe: true
lsi: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      is_post: true

collections:
  docs:
    output: true
